USB_VID = 0x303A
USB_PID = 0x1001
USB_PRODUCT = "WT32-SCO1+"
USB_MANUFACTURER = "Espressif"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 8MB


CIRCUITPY_PARALLELDISPLAY = 1
CIRCUITPY_USB = 1